<salla-modal class="s-login-modal salla-modal s-modal s-modal-container hydrated" id="sign-in-modal">
    <div class=" s-modal-overlay s-modal-entering"></div>
    <div class="s-modal-wrapper">
        <span class="s-modal-spacer s-modal-align-middle">&ZeroWidthSpace;</span>
        <div class="s-modal-body s-modal-align-middle s-modal-xs s-modal-padding s-modal-entering">
            <div class="s-modal-header">
                <button class="s-modal-close sign-in-close" type="button">
                    <span>
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>cancel</title>
                            <path d="M17.885 16l7.057-7.057c0.521-0.521 0.521-1.364 0-1.885s-1.364-0.521-1.885 0l-7.057 7.057-7.057-7.057c-0.521-0.521-1.364-0.521-1.885 0s-0.521 1.364 0 1.885l7.057 7.057-7.057 7.057c-0.521 0.521-0.521 1.364 0 1.885 0.26 0.26 0.601 0.391 0.943 0.391s0.683-0.131 0.943-0.391l7.057-7.057 7.057 7.057c0.26 0.26 0.601 0.391 0.943 0.391s0.683-0.131 0.943-0.391c0.521-0.521 0.521-1.364 0-1.885z"></path>
                        </svg>
                    </span>
                </button>
                <div class="s-modal-header-inner">
                    <slot-fb name="icon" hidden=""></slot-fb>
                    <span slot="icon" class="s-login-modal-header-icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>user</title>
                            <path d="M16 16c4.412 0 8-3.588 8-8s-3.588-8-8-8-8 3.588-8 8 3.588 8 8 8zM16 2.667c2.941 0 5.333 2.392 5.333 5.333s-2.392 5.333-5.333 5.333-5.333-2.392-5.333-5.333 2.392-5.333 5.333-5.333zM16 18.667c-7.476 0-13.333 3.66-13.333 8.333v3.667c0 0.736 0.597 1.333 1.333 1.333s1.333-0.597 1.333-1.333v-3.667c0-3.019 4.984-5.667 10.667-5.667s10.667 2.648 10.667 5.667v3.667c0 0.736 0.597 1.333 1.333 1.333s1.333-0.597 1.333-1.333v-3.667c0-4.673-5.857-8.333-13.333-8.333z"></path>
                        </svg>
                    </span>
                    <div class="s-modal-header-content">
                        <div class="s-modal-title"><?php _e('sign in', 'mahalik'); ?></div>
                    </div>
                </div>
            </div>
            <div class="s-login-modal-wrapper">
                <div class="s-login-modal-tab s-show s-login-modal-active" data-name="login-email">
                    <label class="s-login-modal-label"><?php _e('E-mail', 'mahalik'); ?></label>
                    <form method="POST">
                        <input type="email" placeholder="your@email.com" class="s-login-modal-input s-ltr">
                        <salla-button class="s-login-modal-enter-button s-button-wrap hydrated" type="button">
                            <button class="s-login-modal-enter-button s-button-element s-button-btn s-button-solid s-button-wide s-button-primary s-button-loader-center" loader-position="center" type="button"><span class="s-button-text"><?php _e('Submit', 'mahalik'); ?></span></button>
                        </salla-button>
                    </form>
                </div>
                <salla-verify support-web-auth="true" class="s-hidden hydrated" data-name="otp">
                    <!---->
                    <div class="s-verify-body">
                        <div class="s-verify-message">رقم التحقق مطلوب لاكمال العملية<br> لقد تم إرسال رمز التحقق فى رسالة إليكم</div>
                        <div dir="ltr" class="s-login-modal-currentEmail" slot="email"></div>
                        <input type="hidden" name="code" maxlength="4" required="">
                        <div class="s-verify-codes" dir="ltr"><input type="number" autocomplete="one-time-code" pattern="[0-9]*" inputmode="numeric" maxlength="1" id="otp-1" class="s-verify-input" required=""><input type="number" autocomplete="one-time-code" pattern="[0-9]*" inputmode="numeric" maxlength="1" id="otp-2" class="s-verify-input" required=""><input type="number" autocomplete="one-time-code" pattern="[0-9]*" inputmode="numeric" maxlength="1" id="otp-3" class="s-verify-input" required=""><input type="number" autocomplete="one-time-code" pattern="[0-9]*" inputmode="numeric" maxlength="1" id="otp-4" class="s-verify-input" required=""></div>
                        <div slot="footer" class="s-verify-footer">
                            <salla-button class="s-verify-submit s-button-wrap hydrated" loader-position="center" shape="btn" color="primary" fill="solid" size="medium" width="normal" disabled="" type="button">
                                <!----><button class="s-verify-submit s-button-element s-button-btn s-button-solid s-button-primary s-button-disabled s-button-loader-center" loader-position="center" type="button" disabled=""><span class="s-button-text">تحقق</span></button>
                            </salla-button>
                            <p class="s-verify-resend-message">يمكنك إعادة الإرسال بعد<b class="s-verify-timer"></b></p>
                            <a href="javascript:void(0);" class="s-verify-resend">إرسال</a>
                        </div>
                        <a class="s-verify-back" slot="after-footer" href="javascript:void(0);">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                <title>arrow-right</title>
                                <path d="M29.217 15.465c-0.019-0.044-0.056-0.077-0.080-0.119-0.067-0.116-0.139-0.227-0.236-0.317-0.011-0.009-0.013-0.024-0.024-0.033l-10.667-9.333c-0.553-0.484-1.396-0.429-1.881 0.125-0.484 0.555-0.428 1.396 0.127 1.881l7.996 6.997h-20.452c-0.737 0-1.333 0.597-1.333 1.333s0.596 1.333 1.333 1.333h20.452l-7.996 6.997c-0.555 0.485-0.611 1.327-0.127 1.881 0.264 0.3 0.633 0.455 1.004 0.455 0.312 0 0.625-0.109 0.877-0.331l10.667-9.333c0.011-0.009 0.015-0.024 0.024-0.033 0.097-0.091 0.169-0.201 0.236-0.317 0.024-0.041 0.060-0.075 0.080-0.119 0.073-0.163 0.116-0.343 0.116-0.533s-0.043-0.371-0.116-0.535z"></path>
                            </svg>
                        </a>
                    </div>
                </salla-verify>
                <div data-name="registration" class="s-hidden">
                    <div><label class="s-login-modal-label">اسمك الكريم</label><input type="text" class="s-login-modal-input" placeholder="الاسم الأول"><span class="s-login-modal-error-message"></span></div>
                    <div><label class="s-login-modal-label">الاسم الأخير</label><input type="text" class="s-login-modal-input" placeholder="الاسم الأخير"><span class="s-login-modal-error-message"></span></div>
                    <div class="mb-1.5">
                        <label class="s-login-modal-label">رقم الجوال</label>
                        <salla-tel-input class="s-tel-input hydrated">
                            <div class="iti iti--allow-dropdown iti--separate-dial-code iti--show-flags">
                                <div class="iti__flag-container">
                                    <div class="iti__selected-flag" role="combobox" aria-haspopup="listbox" aria-controls="iti-0__country-listbox" aria-expanded="false" aria-label="Telephone country code" tabindex="0" title="Bangladesh (বাংলাদেশ)">
                                        <div class="iti__flag iti__bd"></div>
                                        <div class="iti__selected-dial-code">+880</div>
                                        <div class="iti__arrow"></div>
                                    </div>
                                    <ul class="iti__country-list iti__hide" id="iti-0__country-listbox" role="listbox" aria-label="List of countries">
                                        <li class="iti__country iti__preferred" tabindex="-1" id="iti-0__item-sa-preferred" role="option" data-dial-code="966" data-country-code="sa" aria-selected="false">
                                            <div class="iti__flag-box">
                                                <div class="iti__flag iti__sa"></div>
                                            </div>
                                            <span class="iti__country-name">Saudi Arabia (&#x202B;المملكة العربية السعودية&#x202C;&lrm;)</span><span class="iti__dial-code">+966</span>
                                        </li>
                                    </ul>
                                </div>
                                <input type="tel" name="phone" enterkeyhint="next" autocomplete="tel" class="s-tel-input-control tel-input s-ltr" data-intl-tel-input-id="0" style="padding-right: 86px;" placeholder="01812-345678">
                            </div>
                            <span class="s-tel-input-error-msg"></span><input type="hidden" name="country_code" value="BD" class="country_code">
                        </salla-tel-input>
                    </div>
                    <div class="mb-1.5 s-hidden"><label class="s-login-modal-label">البريد الإلكتروني</label><input type="email" placeholder="your@email.com" class="s-login-modal-input s-ltr"><span class="s-login-modal-error-message"></span></div>
                    <div class="s-login-modal-custom-fields"></div>
                    <salla-button loader-position="center" class="s-button-wrap hydrated" shape="btn" color="primary" fill="solid" size="medium" width="wide" type="button">
                        <!----><button loader-position="center" type="button" class="undefined s-button-element s-button-btn s-button-solid s-button-wide s-button-primary s-button-loader-center"><span class="s-button-text">التسجيل</span></button>
                    </salla-button>
                </div>
            </div>
        </div>
    </div>
</salla-modal>