<salla-modal class="s-login-modal salla-modal s-modal s-modal-container hydrated" id="sign-in-modal">
    <div class=" s-modal-overlay s-modal-entering"></div>
    <div class="s-modal-wrapper">
        <span class="s-modal-spacer s-modal-align-middle">&ZeroWidthSpace;</span>
        <div class="s-modal-body s-modal-align-middle s-modal-xs s-modal-padding s-modal-entering">
            <div class="s-modal-header">
                <button class="s-modal-close sign-in-close" type="button">
                    <span>
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>cancel</title>
                            <path d="M17.885 16l7.057-7.057c0.521-0.521 0.521-1.364 0-1.885s-1.364-0.521-1.885 0l-7.057 7.057-7.057-7.057c-0.521-0.521-1.364-0.521-1.885 0s-0.521 1.364 0 1.885l7.057 7.057-7.057 7.057c-0.521 0.521-0.521 1.364 0 1.885 0.26 0.26 0.601 0.391 0.943 0.391s0.683-0.131 0.943-0.391l7.057-7.057 7.057 7.057c0.26 0.26 0.601 0.391 0.943 0.391s0.683-0.131 0.943-0.391c0.521-0.521 0.521-1.364 0-1.885z"></path>
                        </svg>
                    </span>
                </button>
                <div class="s-modal-header-inner">
                    <slot-fb name="icon" hidden=""></slot-fb>
                    <span slot="icon" class="s-login-modal-header-icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>user</title>
                            <path d="M16 16c4.412 0 8-3.588 8-8s-3.588-8-8-8-8 3.588-8 8 3.588 8 8 8zM16 2.667c2.941 0 5.333 2.392 5.333 5.333s-2.392 5.333-5.333 5.333-5.333-2.392-5.333-5.333 2.392-5.333 5.333-5.333zM16 18.667c-7.476 0-13.333 3.66-13.333 8.333v3.667c0 0.736 0.597 1.333 1.333 1.333s1.333-0.597 1.333-1.333v-3.667c0-3.019 4.984-5.667 10.667-5.667s10.667 2.648 10.667 5.667v3.667c0 0.736 0.597 1.333 1.333 1.333s1.333-0.597 1.333-1.333v-3.667c0-4.673-5.857-8.333-13.333-8.333z"></path>
                        </svg>
                    </span>
                    <div class="s-modal-header-content">
                        <div class="s-modal-title"><?php _e('sign in', 'mahalik'); ?></div>
                    </div>
                </div>
            </div>


            <div class="s-login-modal-wrapper">
                <div class="s-login-modal-tab modal-tab" data-name="login-email">
                    <label class="s-login-modal-label"><?php _e('E-mail', 'mahalik'); ?></label>
                    <form method="POST">
                        <input type="email" name="email" placeholder="your@email.com" class="s-login-modal-input s-ltr" required>
                        <!-- <span class="s-login-modal-error-message">* تأكد من صحة البريد الإلكتروني</span> -->
                        <salla-button class="s-login-modal-enter-button s-button-wrap hydrated">
                            <button class="s-login-modal-enter-button s-button-element s-button-btn s-button-solid s-button-wide s-button-primary s-button-loader-center" type="submit"><span class="s-button-text"><?php _e('Submit', 'mahalik'); ?></span>
                            </button>
                        </salla-button>
                    </form>
                </div>


                <form class="hydrated s-hidden modal-tab" data-name="otp">
                    <div class="s-verify-body">
                        <div class="s-verify-message">
                            <?php _e('The verification number is required to complete the process', 'mahalik'); ?>
                            <br>
                            <?php _e('A verification code has been sent to you in a message', 'mahalik'); ?>
                        </div>
                        <div dir="ltr" class="s-login-modal-currentEmail">your@email.com</div>
                        <input type="hidden" name="code" id="emailverificationCode">
                        <input type="hidden" name="publicKey" id="publicKey">
                        <div class="s-verify-codes" dir="ltr">
                            <input type="number" class="email-otp-input s-verify-input" pattern="\d" maxlength="1">
                            <input type="number" class="email-otp-input s-verify-input" pattern="\d" maxlength="1" disabled>
                            <input type="number" class="email-otp-input s-verify-input" pattern="\d" maxlength="1" disabled>
                            <input type="number" class="email-otp-input s-verify-input" pattern="\d" maxlength="1" disabled>
                        </div>
                        <span class="s-verify-error-message" style="display: none;"><?php _e('Invalid verification code', 'mahalik'); ?></span>
                        <div slot="footer" class="s-verify-footer">

                            <button type="submit" class="s-verify-submit s-button-element s-button-btn s-button-solid s-button-primary  s-button-loader-center">
                                <span class="s-button-text"><?php _e('Submit', 'mahalik'); ?></span>
                            </button>
                            <a href="javascript:void(0);" class="s-verify-resend" style="display: none;">Send</a>

                            <p class="s-verify-resend-message"><?php _e('You will be able to resend after') ?><b class="s-verify-timer"></b></p>
                        </div>
                        <a class="s-verify-back" slot="after-footer" href="javascript:void(0);">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                <title>arrow-right</title>
                                <path d="M29.217 15.465c-0.019-0.044-0.056-0.077-0.080-0.119-0.067-0.116-0.139-0.227-0.236-0.317-0.011-0.009-0.013-0.024-0.024-0.033l-10.667-9.333c-0.553-0.484-1.396-0.429-1.881 0.125-0.484 0.555-0.428 1.396 0.127 1.881l7.996 6.997h-20.452c-0.737 0-1.333 0.597-1.333 1.333s0.596 1.333 1.333 1.333h20.452l-7.996 6.997c-0.555 0.485-0.611 1.327-0.127 1.881 0.264 0.3 0.633 0.455 1.004 0.455 0.312 0 0.625-0.109 0.877-0.331l10.667-9.333c0.011-0.009 0.015-0.024 0.024-0.033 0.097-0.091 0.169-0.201 0.236-0.317 0.024-0.041 0.060-0.075 0.080-0.119 0.073-0.163 0.116-0.343 0.116-0.533s-0.043-0.371-0.116-0.535z"></path>
                            </svg>
                        </a>
                    </div>
                </form>


                <form data-name="registration" class="s-hidden modal-tab">
                    <input type="hidden" name="session" id="register-session">
                    <div>
                        <label class="s-login-modal-label"><?php _e('Your honorable name'); ?></label>
                        <input name="firstName" type="text" class="s-login-modal-input" placeholder="<?php _e('First Name', 'mahalik'); ?>" required>
                        <span class="s-login-modal-error-message"></span>
                    </div>
                    <div>
                        <label class="s-login-modal-label"><?php _e('Last Name', 'mahalik'); ?></label>
                        <input name="lastName" type="text" class="s-login-modal-input" placeholder="<?php _e('Last Name', 'mahalik'); ?>" required>
                        <span class="s-login-modal-error-message"></span>
                    </div>
                    <div class="mb-1.5">
                        <label class="s-login-modal-label"><?php _e('Phone Number', 'mahalik'); ?></label>
                        <div class="iti iti--allow-dropdown iti--separate-dial-code iti--show-flags">
                            <input type="tel" name="phone" class="s-tel-input-control tel-input s-ltr" style="padding-right: 86px;" placeholder="01812-345678" required>
                        </div>
                    </div>

                    <div class="s-login-modal-custom-fields"></div>

                    <button type="submit" class="user-sign-button undefined s-button-element s-button-btn s-button-solid s-button-wide s-button-primary s-button-loader-center"><span class="s-button-text"><?php _e('Sign Up'); ?></span></button>

                    <a class="s-verify-back" slot="after-footer" href="javascript:void(0);">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>arrow-right</title>
                            <path d="M29.217 15.465c-0.019-0.044-0.056-0.077-0.080-0.119-0.067-0.116-0.139-0.227-0.236-0.317-0.011-0.009-0.013-0.024-0.024-0.033l-10.667-9.333c-0.553-0.484-1.396-0.429-1.881 0.125-0.484 0.555-0.428 1.396 0.127 1.881l7.996 6.997h-20.452c-0.737 0-1.333 0.597-1.333 1.333s0.596 1.333 1.333 1.333h20.452l-7.996 6.997c-0.555 0.485-0.611 1.327-0.127 1.881 0.264 0.3 0.633 0.455 1.004 0.455 0.312 0 0.625-0.109 0.877-0.331l10.667-9.333c0.011-0.009 0.015-0.024 0.024-0.033 0.097-0.091 0.169-0.201 0.236-0.317 0.024-0.041 0.060-0.075 0.080-0.119 0.073-0.163 0.116-0.343 0.116-0.533s-0.043-0.371-0.116-0.535z"></path>
                        </svg>
                    </a>
                </form>

            </div>
        </div>
    </div>
</salla-modal>