<?php

/**
 * The template for displaying product content in the single-product.php template
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/content-single-product.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see     https://woo.com/document/template-structure/
 * @package WooCommerce\Templates
 * @version 3.6.0
 */

defined('ABSPATH') || exit;

global $product;

/**
 * Hook: woocommerce_before_single_product.
 *
 * @hooked woocommerce_output_all_notices - 10
 */
do_action('woocommerce_before_single_product');

if (post_password_required()) {
    echo get_the_password_form(); // WPCS: XSS ok.
    return;
}
?>

<div <?php wc_product_class('three-cols-wrap relative flex flex-col md:flex-row pb-5 lg:pb-20 has-no-options', $product); ?> id="product-<?php the_ID(); ?>">

    <div class="product-slider  has-one-image  img-is-contain has-promotion-title">
        <div class="details-slider-wrapper has-less-slides">
            <salla-slider id="details-slider-1237402650" class="details-slider circle-arrows has-thumbs-grid s-slider-wrapper thumbs-slider s-slider-has-notitle s-slider-v-centered s-slider-horizontal s-slider-with-grid-thumbs hydrated" type="thumbs" loop="false" listen-to-thumbnails-option="" arrows-centered="" auto-height="false" grid-thumbs="true" block-title="" block-subtitle="" display-all-url="" show-controls="" direction="rtl">
                <!---->
                <div class="s-slider-block__title">
                    <div class="s-slider-block__title-left">
                        <div class="s-slider-block__title-nav" dir="rtl">
                            <button aria-label="Previous slide" class="s-slider-prev s-slider-nav-arrow swiper-button-disabled swiper-button-lock" disabled="" tabindex="-1" aria-controls="swiper-wrapper-82609295a8e1ec5f" aria-disabled="true">
                                <span class="s-slider-button-icon">
                                    <!-- Generated by IcoMoon.io -->
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                        <title>keyboard_arrow_right</title>
                                        <path d="M11.438 22.479l6.125-6.125-6.125-6.125 1.875-1.875 8 8-8 8z"></path>
                                    </svg>
                                </span>
                            </button>
                            <button aria-label="Next slide" class="s-slider-next s-slider-nav-arrow swiper-button-disabled swiper-button-lock" disabled="" tabindex="-1" aria-controls="swiper-wrapper-82609295a8e1ec5f" aria-disabled="true">
                                <span class="s-slider-button-icon">
                                    <!-- Generated by IcoMoon.io -->
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                        <title>keyboard_arrow_left</title>
                                        <path d="M20.563 22.104l-1.875 1.875-8-8 8-8 1.875 1.875-6.125 6.125z"></path>
                                    </svg>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="swiper s-slider-container swiper-initialized swiper-horizontal swiper-pointer-events swiper-rtl swiper-backface-hidden" dir="rtl">
                    <span class="promotion-badge">
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">New</font>
                        </font>
                    </span>
                    <div class="swiper-wrapper s-slider-swiper-wrapper" id="swiper-wrapper-82609295a8e1ec5f" aria-live="polite">
                        <div class="swiper-slide swiper-slide-active" role="group" aria-label="1/1" style="width: 696px; margin-left: 30px;">
                            <a data-fslightbox="product_1237402650" data-img-id="119907204" data-slid-index="0" data-caption="image" data-infinite="false" data-type="image" href="https://sbs-sa-jasminbeauty.odoo.com/channel/image/product.template/59173/image_1920/ناسيفيك-مجموعة-الترطيب-الذهبية.png" aria-label="Nacific Gold Moisturizing Set">



                                <img fetchpriority="high" loading="eager" src="<?php echo get_the_post_thumbnail_url(get_the_ID()); ?>" alt="image" style="object-fit: contain" class="h-full w-full ">
                            </a>
                        </div>
                    </div>
                    <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span>
                </div>
            </salla-slider>
        </div>
    </div>
    <div class="main-content ">
        <div class="general-products-info">
            <div>
                <?php the_title('<h1 class="text-2xl lg:text-3xl font-bold text-gray-800">', '</h1>'); ?>
                <h3 class="product-entry__sub-title">
                    <?php echo get_post_meta(get_the_ID(), 'product_subheading', true); ?>
                </h3>
            </div>
            <small class="color-grey">
                <?php _e('The price includes tax', 'mahalik'); ?>
            </small>
            <div class="share-rate-area ">
                <div class="heart-icon ">
                    <salla-button class="btn--wishlist s-button-wrap hydrated" data-id="1237402650" shape="link" loader-position="center" color="gray" fill="solid" size="medium" width="normal" type="button">
                        <!----><button class="btn--wishlist s-button-element s-button-link s-button-solid s-button-gray-link s-button-loader-center" data-id="1237402650" shape="link" loader-position="center" type="button"><span class="s-button-text">
                                <i class="sicon-heart"></i>
                            </span></button>
                    </salla-button>
                </div>
                <div class="hidden md:flex">
                    <salla-social-share url="" url-name="" platforms="facebook,twitter,whatsapp,email,copy_link" class="hydrated">
                        <!---->
                        <div class="s-social-share-wrapper">
                            <slot-fb name="widget">
                                <salla-button aria-label="Share" class="s-social-share-btn s-button-wrap hydrated" shape="icon" color="light" fill="outline" size="medium" width="normal" type="button">
                                    <!---->
                                    <button aria-label="Share" class="s-social-share-btn s-button-element s-button-icon s-button-outline s-button-light-outline s-button-loader-center" type="button">
                                        <span class="s-button-text">
                                            <span>
                                                <!-- Generated by IcoMoon.io -->
                                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                    <title>share-alt</title>
                                                    <path d="M26.667 21.333c-1.699 0-3.196 0.812-4.173 2.052l-11.912-5.211c0.044-0.276 0.085-0.553 0.085-0.841 0-0.472-0.081-0.923-0.197-1.359l12.361-6.952c0.971 1.009 2.328 1.644 3.836 1.644 2.941 0 5.333-2.392 5.333-5.333s-2.392-5.333-5.333-5.333-5.333 2.392-5.333 5.333c0 0.472 0.081 0.923 0.197 1.359l-12.361 6.952c-0.971-1.009-2.328-1.644-3.836-1.644-2.941 0-5.333 2.392-5.333 5.333s2.392 5.333 5.333 5.333c1.699 0 3.196-0.812 4.173-2.052l11.912 5.211c-0.044 0.276-0.085 0.553-0.085 0.841 0 2.941 2.392 5.333 5.333 5.333s5.333-2.392 5.333-5.333-2.392-5.333-5.333-5.333zM26.667 2.667c1.471 0 2.667 1.196 2.667 2.667s-1.196 2.667-2.667 2.667-2.667-1.196-2.667-2.667 1.196-2.667 2.667-2.667zM5.333 20c-1.471 0-2.667-1.196-2.667-2.667s1.196-2.667 2.667-2.667 2.667 1.196 2.667 2.667-1.196 2.667-2.667 2.667zM26.667 29.333c-1.471 0-2.667-1.196-2.667-2.667s1.196-2.667 2.667-2.667 2.667 1.196 2.667 2.667-1.196 2.667-2.667 2.667z"></path>
                                                </svg>
                                            </span>
                                        </span>
                                    </button>
                                </salla-button>
                            </slot-fb>
                            <ul class="s-social-share-list a2a_kit share" data-a2a-url="https://lamsah.co/ar/%D9%86%D8%A7%D8%B3%D9%8A%D9%81%D9%8A%D9%83-%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A9-%D8%A7%D9%84%D8%AA%D8%B1%D8%B7%D9%8A%D8%A8-%D8%A7%D9%84%D8%B0%D9%87%D8%A8%D9%8A%D8%A9/p1237402650" data-a2a-title="ناسيفيك مجموعة الترطيب الذهبية - لمسة ستور للعناية والتجميل" style="line-height: 16px;">
                                <li>
                                    <a class="a2a_button_facebook" aria-label="Share via facebook" target="_blank" rel="nofollow noopener" href="/#facebook">
                                        <span class="s-social-share-icon">
                                            <!-- Generated by IcoMoon.io -->
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                <title>facebook</title>
                                                <path d="M19 32h-6c-0.552 0-1-0.448-1-1v0-13h-3c-0.552 0-1-0.448-1-1v0-5c0-0.552 0.448-1 1-1v0h3v-4c0-3.866 3.134-7 7-7v0h4c0.552 0 1 0.448 1 1v0 5c0 0.552-0.448 1-1 1v0h-2c-0.552 0-1 0.448-1 1v0 3h5c0.552 0 1 0.448 1 1 0 0.134-0.026 0.262-0.074 0.379l0.002-0.007-2 5c-0.152 0.371-0.51 0.628-0.928 0.628h-3v13c0 0.552-0.448 1-1 1v0zM14 30h4v-13c0-0.552 0.448-1 1-1v0h3.324l1.2-3h-4.524c-0.552 0-1-0.448-1-1v0-4c0-1.657 1.343-3 3-3v0h1v-3h-3c-2.761 0-5 2.239-5 5v0 5c0 0.552-0.448 1-1 1v0h-3v3h3c0.552 0 1 0.448 1 1v0z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="a2a_button_twitter" aria-label="Share via twitter" target="_blank" rel="nofollow noopener" href="/#twitter">
                                        <span class="s-social-share-icon">
                                            <!-- Generated by IcoMoon.io -->
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                <title>twitter</title>
                                                <path d="M10.436 30c-0.012 0-0.026 0-0.041 0-3.691 0-7.129-1.088-10.009-2.961l0.071 0.043c-0.279-0.181-0.46-0.49-0.46-0.842 0-0.123 0.022-0.24 0.063-0.349l-0.002 0.007c0.148-0.387 0.516-0.657 0.948-0.657 0.042 0 0.083 0.003 0.123 0.007l-0.005-0c0.399 0.049 0.86 0.077 1.328 0.077 1.836 0 3.57-0.432 5.108-1.199l-0.066 0.030c-1.941-0.823-3.42-2.412-4.079-4.377l-0.015-0.051c-0.033-0.095-0.053-0.205-0.053-0.32 0-0.255 0.096-0.488 0.253-0.665l-0.001 0.001 0.062-0.062c-1.511-1.323-2.46-3.254-2.462-5.408v-0c0-0 0-0.001 0-0.001 0-0.374 0.194-0.703 0.488-0.89l0.004-0.003c0.115-0.070 0.25-0.121 0.393-0.145l0.007-0.001c-0.534-0.978-0.848-2.141-0.848-3.379 0-1.329 0.362-2.574 0.994-3.641l-0.018 0.033c0.176-0.301 0.498-0.501 0.866-0.501 0.312 0 0.591 0.143 0.774 0.367l0.001 0.002c2.627 3.213 6.397 5.405 10.682 5.953l0.082 0.009c0-0.098 0-0.2 0-0.302 0-0.001 0-0.002 0-0.002 0-3.949 3.201-7.15 7.15-7.15 1.852 0 3.54 0.704 4.81 1.86l-0.006-0.005c1.165-0.288 2.19-0.719 3.127-1.282l-0.051 0.028c0.146-0.088 0.323-0.141 0.512-0.141 0.552 0 1 0.448 1 1 0 0.109-0.017 0.214-0.050 0.312l0.002-0.007c-0.151 0.464-0.324 0.861-0.531 1.237l0.019-0.037c0.117-0.052 0.253-0.082 0.396-0.082 0.552 0 1 0.448 1 1 0 0.208-0.064 0.401-0.172 0.561l0.002-0.004c-0.812 1.212-1.772 2.247-2.87 3.114l-0.028 0.022c0 0.1 0 0.2 0 0.306 0 0.051 0.001 0.111 0.001 0.171 0 10.12-8.204 18.324-18.324 18.324-0.062 0-0.124-0-0.186-0.001l0.009 0zM5 27.084c1.616 0.58 3.481 0.916 5.424 0.916 0.004 0 0.008 0 0.013 0h-0.001c0.048 0 0.104 0.001 0.161 0.001 9.027 0 16.344-7.317 16.344-16.344 0-0.055-0-0.11-0.001-0.165l0 0.008c0-0.256 0-0.502-0.022-0.746-0.001-0.014-0.001-0.031-0.001-0.049 0-0.335 0.165-0.632 0.418-0.813l0.003-0.002q0.312-0.222 0.6-0.466l-0.364 0.052c-0.038 0.005-0.082 0.008-0.126 0.008-0.552 0-1-0.448-1-1 0-0.363 0.193-0.68 0.482-0.856l0.004-0.003q0.222-0.134 0.428-0.286c-0.3 0.082-0.6 0.154-0.912 0.214-0.059 0.012-0.127 0.020-0.197 0.020-0.286 0-0.544-0.12-0.727-0.313l-0-0c-0.943-1.007-2.28-1.634-3.764-1.634-2.845 0-5.152 2.307-5.152 5.152 0 0.001 0 0.002 0 0.002v-0c-0 0.020-0 0.043-0 0.066 0 0.395 0.043 0.781 0.125 1.151l-0.007-0.035c0.017 0.069 0.027 0.148 0.027 0.23 0 0.242-0.086 0.463-0.228 0.636l0.001-0.002c-0.177 0.219-0.445 0.358-0.746 0.358-0.024 0-0.047-0.001-0.071-0.003l0.003 0c-4.85-0.253-9.167-2.342-12.31-5.577l-0.004-0.005c-0.098 0.376-0.155 0.808-0.155 1.253 0 1.778 0.902 3.345 2.272 4.27l0.018 0.012c0.27 0.182 0.446 0.487 0.446 0.832 0 0.552-0.448 1-1 1-0.008 0-0.015-0-0.023-0l0.001 0c-0.548-0.010-1.074-0.082-1.577-0.21l0.047 0.010c0.554 1.812 2.029 3.181 3.866 3.574l0.034 0.006c0.458 0.097 0.797 0.499 0.797 0.979 0 0.456-0.305 0.841-0.722 0.961l-0.007 0.002c-0.412 0.117-0.89 0.198-1.383 0.225l-0.017 0.001c0.926 1.304 2.415 2.156 4.105 2.2l0.007 0c0.546 0.009 0.984 0.453 0.984 1 0 0.319-0.15 0.603-0.382 0.787l-0.002 0.002c-1.596 1.249-3.522 2.154-5.625 2.568l-0.085 0.014z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="a2a_button_whatsapp" aria-label="Share via whatsapp" target="_blank" rel="nofollow noopener" href="/#whatsapp">
                                        <span class="s-social-share-icon">
                                            <!-- Generated by IcoMoon.io -->
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                <title>whatsapp</title>
                                                <path d="M16 32c-0.008 0-0.018 0-0.028 0-3.1 0-5.993-0.887-8.439-2.421l0.066 0.039-7.2 2.3 2.336-6.964c-1.713-2.492-2.736-5.575-2.736-8.897 0-0.020 0-0.040 0-0.060v0.003c0.009-8.833 7.167-15.991 15.999-16h0.001c8.837 0 16 7.163 16 16s-7.163 16-16 16v0zM7.906 27.424l0.4 0.264c2.169 1.449 4.837 2.312 7.707 2.312 7.732 0 14-6.268 14-14s-6.268-14-14-14c-0.004 0-0.009 0-0.013 0h0.001c-7.729 0.008-13.992 6.271-14 13.999v0.001c-0 0.010-0 0.021-0 0.032 0 3.072 1 5.909 2.693 8.206l-0.027-0.038 0.304 0.416-1.4 4.2zM20.716 24.958c-1.684-0.131-3.237-0.574-4.641-1.271l0.073 0.033c-3.098-1.456-5.634-3.668-7.438-6.405l-0.042-0.067c-1.102-1.357-1.819-3.067-1.962-4.938l-0.002-0.030c-0.001-0.036-0.001-0.078-0.001-0.12 0-1.575 0.66-2.995 1.719-4l0.002-0.002c0.547-0.52 1.289-0.839 2.105-0.839 0.033 0 0.066 0.001 0.099 0.002l-0.005-0c0.2 0 0.378 0 0.542 0.018 0.016-0.001 0.035-0.001 0.054-0.001 0.815 0 1.502 0.549 1.711 1.298l0.003 0.012 0.324 0.782c0.376 0.906 0.858 2.068 0.942 2.244 0.144 0.251 0.23 0.552 0.23 0.873 0 0.286-0.068 0.557-0.188 0.797l0.005-0.010c-0.149 0.307-0.332 0.57-0.55 0.802l0.002-0.002c-0.148 0.168-0.248 0.274-0.346 0.378s-0.172 0.18-0.26 0.284c0.575 0.92 1.237 1.713 1.992 2.406l0.008 0.008c0.829 0.758 1.802 1.373 2.872 1.8l0.064 0.022c0.369-0.266 0.672-0.6 0.896-0.985l0.008-0.015 0.174-0.232c0.328-0.484 0.875-0.798 1.495-0.798 0.249 0 0.487 0.051 0.703 0.142l-0.012-0.004c0.492 0.168 2.922 1.372 2.946 1.384l0.228 0.11c0.415 0.149 0.758 0.417 0.996 0.763l0.004 0.007c0.107 0.349 0.169 0.75 0.169 1.166 0 0.591-0.125 1.153-0.349 1.661l0.010-0.026c-0.702 1.368-1.983 2.353-3.511 2.637l-0.031 0.005c-0.309 0.071-0.663 0.112-1.028 0.112-0.004 0-0.007 0-0.011 0h0.001zM10.632 9.318c-0.028-0.002-0.062-0.004-0.095-0.004-0.245 0-0.472 0.076-0.659 0.206l0.004-0.002c-0.726 0.651-1.18 1.591-1.18 2.638 0 0.044 0.001 0.087 0.002 0.13l-0-0.006c0.122 1.404 0.662 2.662 1.495 3.671l-0.009-0.011 0.12 0.168c1.627 2.491 3.865 4.46 6.504 5.723l0.096 0.041c3.136 1.288 3.916 1.124 4.426 1.014 0.87-0.159 1.601-0.656 2.067-1.347l0.007-0.011c0.12-0.316 0.204-0.682 0.237-1.063l0.001-0.015-0.040-0.018-0.256-0.124c-0.8-0.4-2.46-1.2-2.734-1.292l-0.058 0.184c-0.346 0.501-0.684 0.934-1.045 1.347l0.015-0.017c-0.344 0.349-0.821 0.565-1.349 0.565-0.28 0-0.546-0.061-0.785-0.17l0.012 0.005c-1.403-0.547-2.609-1.301-3.646-2.239l0.010 0.009c-0.975-0.891-1.81-1.912-2.486-3.039l-0.034-0.061c-0.152-0.244-0.242-0.54-0.242-0.857 0-0.463 0.191-0.88 0.499-1.178l0-0c0.13-0.162 0.264-0.302 0.4-0.444l0.236-0.256c0.091-0.096 0.177-0.201 0.254-0.311l0.006-0.009c-0.158-0.36-0.622-1.472-0.988-2.352l-0.322-0.772-0.038-0.086c-0.188-0.010-0.302-0.016-0.426-0.016zM12.462 12.442v0.012z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="a2a_button_email" aria-label="Share via email" target="_blank" rel="nofollow noopener" href="/#email">
                                        <span class="s-social-share-icon">
                                            <!-- Generated by IcoMoon.io -->
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                <title>mail</title>
                                                <path d="M28 2.667h-24c-2.205 0-4 1.795-4 4v18.667c0 2.205 1.795 4 4 4h24c2.205 0 4-1.795 4-4v-18.667c0-2.205-1.795-4-4-4zM29.333 25.333c0 0.735-0.599 1.333-1.333 1.333h-24c-0.735 0-1.333-0.599-1.333-1.333v-12.685l10.54 4.865c0.888 0.409 1.84 0.613 2.793 0.613s1.907-0.204 2.793-0.615l10.54-4.864zM29.333 9.711l-11.657 5.38c-1.065 0.492-2.288 0.492-3.353 0l-11.656-5.38v-3.044c0-0.735 0.599-1.333 1.333-1.333h24c0.735 0 1.333 0.599 1.333 1.333z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="a2a_button_copy_link" aria-label="Share Via copy_link" target="_blank" rel="nofollow noopener" href="/#copy_link">
                                        <span class="s-social-share-icon">
                                            <!-- Generated by IcoMoon.io -->
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                <title>link</title>
                                                <path d="M19.247 23.019l-4.189 4.189c-2.831 2.831-7.435 2.831-10.265 0-1.371-1.372-2.125-3.193-2.125-5.132s0.755-3.761 2.125-5.133l4.189-4.191c0.521-0.521 0.521-1.364 0-1.885s-1.364-0.521-1.885 0l-4.189 4.191c-1.875 1.875-2.907 4.367-2.907 7.019s1.032 5.143 2.907 7.017 4.368 2.907 7.019 2.907 5.143-1.032 7.017-2.908l4.189-4.189c0.521-0.521 0.521-1.364 0-1.885s-1.364-0.52-1.885 0.001zM22.276 9.724c-0.521-0.521-1.364-0.521-1.885 0l-10.667 10.667c-0.521 0.521-0.521 1.364 0 1.885 0.26 0.26 0.601 0.391 0.943 0.391s0.683-0.131 0.943-0.391l10.667-10.667c0.521-0.521 0.521-1.364 0-1.885zM29.093 2.908c-1.875-1.876-4.368-2.908-7.019-2.908s-5.143 1.032-7.017 2.908l-4.189 4.188c-0.521 0.521-0.521 1.364 0 1.885s1.364 0.521 1.885 0l4.189-4.189c2.831-2.831 7.435-2.831 10.265 0 1.371 1.372 2.125 3.193 2.125 5.132s-0.755 3.761-2.125 5.133l-4.189 4.191c-0.521 0.521-0.521 1.364 0 1.885 0.26 0.26 0.601 0.391 0.943 0.391s0.683-0.131 0.943-0.391l4.189-4.191c1.875-1.875 2.907-4.367 2.907-7.019s-1.032-5.143-2.907-7.016z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </salla-social-share>
                </div>
            </div>
            <div class="installment-wrap">
                <salla-installment price="67.05" class="hydrated">
                    <div id="tabbyPromoWrapper">
                        <div id="tabbyPromo">
                            <div class="styles__tabby-snippet--750cf">
                                <div></div>
                            </div>
                        </div>
                    </div>
                </salla-installment>
            </div>
            <div class="details-list">
                <div class="details-list__item">
                    <span class="details-list__item-label">
                        <i class="sicon-barcode"></i>
                        <span class="text">
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">Model number</font>
                            </font>
                        </span>
                    </span>
                    <span>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">8809517461777</font>
                        </font>
                    </span>
                </div>
            </div>
            <salla-quick-order class="hydrated"></salla-quick-order>
        </div>
        <div class="product-options form product-form flex flex-col space-y-2.5 sm:space-y-5 " id="single-product-form">
            <input type="hidden" name="id" value="1237402650">
            <div class="flex border bg-white space-y-2.5 sm:space-y-5 mt-2.5 sm:mt-5 flex-col p-2.5 sm:p-5 rounded ">
                <div class="flex justify-between items-center">
                    <div class="flex flex-col whitespace-nowrap rtl:space-x-reverse space-x-1">
                        <h4 class="total-price text-black font-bold text-xl inline-block">
                            <?php echo wc_price($product->get_price()); ?>
                        </h4>
                    </div>
                    <div>
                        <input type="hidden" name="id" value="1237402650">
                        <salla-quantity-input max="28" value="1" name="quantity" class="border-gray-200 flex justify-end s-quantity-input hydrated">
                            <!---->
                            <div class="s-quantity-input-container">
                                <button class="s-quantity-input-increase-button s-quantity-input-button" type="button">
                                    <span>
                                        <!-- Generated by IcoMoon.io -->
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                            <title>add</title>
                                            <path d="M26.667 14.667h-9.333v-9.333c0-0.736-0.597-1.333-1.333-1.333s-1.333 0.597-1.333 1.333v9.333h-9.333c-0.736 0-1.333 0.597-1.333 1.333s0.597 1.333 1.333 1.333h9.333v9.333c0 0.736 0.597 1.333 1.333 1.333s1.333-0.597 1.333-1.333v-9.333h9.333c0.736 0 1.333-0.597 1.333-1.333s-0.597-1.333-1.333-1.333z"></path>
                                        </svg>
                                    </span>
                                </button>
                                <input class="s-quantity-input-input" max="28" name="quantity" min="1">
                                <button class="s-quantity-input-decrease-button s-quantity-input-button" type="button">
                                    <span>
                                        <!-- Generated by IcoMoon.io -->
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                            <title>minus</title>
                                            <path d="M26.667 14.667h-21.333c-0.736 0-1.333 0.597-1.333 1.333s0.597 1.333 1.333 1.333h21.333c0.736 0 1.333-0.597 1.333-1.333s-0.597-1.333-1.333-1.333z"></path>
                                        </svg>
                                    </span>
                                </button>
                            </div>
                        </salla-quantity-input>
                    </div>
                </div>
                <salla-add-product-button quick-buy="" amount="67.05" class="text-white block s-add-product-button-with-quick-buy hydrated" product-status="sale" product-type="product" product-id="1237402650" loader-position="end" type="submit" width="wide">


                    <salla-button quick-buy="" amount="67.05" product-status="sale" product-type="product" product-id="1237402650" loader-position="center" class="s-button-wrap hydrated" shape="btn" color="primary" fill="solid" size="medium" width="wide" type="submit">
                        <!----><button quick-buy="" amount="67.05" product-status="sale" product-type="product" product-id="1237402650" loader-position="center" type="submit" class="undefined s-button-element s-button-btn s-button-solid s-button-wide s-button-primary s-button-loader-center"><span class="s-button-text"><span class="flex items-center gap-2.5">
                                    <i class="text-[16px] sicon-shopping"></i>
                                    <font style="vertical-align: inherit;">
                                        <font style="vertical-align: inherit;">
                                            Add to cart
                                        </font>
                                    </font>
                                </span></span></button>
                    </salla-button>
                    <?php

                    // echo do_shortcode('[add_to_cart id="' . get_the_ID() . '"]');
                    // // Ensure the product is variable or simple
                    // if ($product->is_type('variable')) {
                    //     // For variable products
                    //     woocommerce_variable_add_to_cart();
                    // } elseif ($product->is_type('simple')) {
                    //     // For simple products
                    //     // woocommerce_simple_add_to_cart();
                    // }
                    ?>
            </div>


            <salla-quick-buy quick-buy="" product-status="sale" product-type="product" product-id="1237402650" loader-position="end" width="wide" amount="67.05" class="hydrated">
                <salla-button class="s-quick-buy-button s-button-wrap hydrated" shape="btn" color="primary" fill="outline" size="medium" width="wide" type="button">
                    <!---->
                    <button class="s-quick-buy-button s-button-element s-button-btn s-button-outline s-button-wide s-button-primary-outline s-button-loader-after" type="button">
                        <span class="s-button-text">
                            <span>
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                    <title>full-wallet</title>
                                    <path d="M29 12h-26c-0.668-0.008-1.284-0.226-1.787-0.59l0.009 0.006c-0.744-0.552-1.222-1.428-1.222-2.416 0-1.657 1.343-3 2.999-3h6c0.552 0 1 0.448 1 1s-0.448 1-1 1v0h-6c-0.552 0-1 0.448-1 1 0 0.326 0.156 0.616 0.397 0.798l0.002 0.002c0.167 0.12 0.374 0.194 0.599 0.2l0.001 0h26c0.552 0 1 0.448 1 1s-0.448 1-1 1v0zM27 12c-0.552 0-1-0.448-1-1v0-3h-3c-0.552 0-1-0.448-1-1s0.448-1 1-1v0h4c0.552 0 1 0.448 1 1v0 4c0 0.552-0.448 1-1 1v0zM29 30h-26c-1.657 0-3-1.343-3-3v0-18c0-0.552 0.448-1 1-1s1 0.448 1 1v0 18c0 0.552 0.448 1 1 1v0h25v-5c0-0.552 0.448-1 1-1s1 0.448 1 1v0 6c0 0.552-0.448 1-1 1v0zM29 18c-0.552 0-1-0.448-1-1v0-6c0-0.552 0.448-1 1-1s1 0.448 1 1v0 6c0 0.552-0.448 1-1 1v0zM31 24h-7c-2.209 0-4-1.791-4-4s1.791-4 4-4v0h7c0.552 0 1 0.448 1 1v0 6c0 0.552-0.448 1-1 1v0zM24 18c-1.105 0-2 0.895-2 2s0.895 2 2 2v0h6v-4zM25 12c-0.001 0-0.001 0-0.002 0-0.389 0-0.726-0.222-0.891-0.546l-0.003-0.006-3.552-7.106-2.306 1.152c-0.13 0.066-0.284 0.105-0.447 0.105-0.552 0-1-0.448-1-1 0-0.39 0.223-0.727 0.548-0.892l0.006-0.003 3.2-1.6c0.13-0.067 0.284-0.106 0.447-0.106 0.39 0 0.727 0.223 0.892 0.548l0.003 0.006 4 8c0.067 0.13 0.106 0.285 0.106 0.448 0 0.552-0.448 1-1 1v0zM21 12c-0.001 0-0.001 0-0.002 0-0.389 0-0.726-0.222-0.891-0.546l-0.003-0.006-3.552-7.106-15.104 7.552c-0.13 0.066-0.284 0.105-0.447 0.105-0.552 0-1-0.448-1-1 0-0.39 0.223-0.727 0.548-0.892l0.006-0.003 16-8c0.13-0.067 0.284-0.106 0.447-0.106 0.39 0 0.727 0.223 0.892 0.548l0.003 0.006 4 8c0.067 0.13 0.106 0.285 0.106 0.448 0 0.552-0.448 1-1 1-0.001 0-0.001 0-0.002 0h0z"></path>
                                </svg>
                            </span>
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">Buy now</font>
                            </font>
                        </span>
                    </button>
                </salla-button>
            </salla-quick-buy>
            </salla-add-product-button>


        </div>
    </div>
</div>









<?php
$swiper_id = uniqid('swiper_related_');
?>
<section style="margin-top: 8rem;" class="s-block s-block--best-offers container overflow-hidden">

    <salla-slider type="carousel" class="s-slider-wrapper carousel-slider s-slider-horizontal hydrated">
        <div class="s-slider-block__title">
            <div class="s-slider-block__title-right">
                <h2><?php _e('Products you may like', 'mahalik'); ?></h2>
            </div>
            <div class="s-slider-block__title-left">
                <div class="s-slider-block__title-nav">
                    <button aria-label="Previous slide" class="<?php echo $swiper_id; ?>-prev s-slider-prev s-slider-nav-arrow">
                        <span class="s-slider-button-icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                <title>keyboard_arrow_right</title>
                                <path d="M11.438 22.479l6.125-6.125-6.125-6.125 1.875-1.875 8 8-8 8z"></path>
                            </svg>
                        </span>
                    </button>
                    <button aria-label="Next slide" class="<?php echo $swiper_id; ?>-next s-slider-next s-slider-nav-arrow">
                        <span class="s-slider-button-icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                <title>keyboard_arrow_left</title>
                                <path d="M20.563 22.104l-1.875 1.875-8-8 8-8 1.875 1.875-6.125 6.125z"></path>
                            </svg>
                        </span>
                    </button>
                </div>
            </div>
        </div>
        <div class=" <?php echo $swiper_id; ?> s-slider-container swiper-initialized swiper-horizontal swiper-pointer-events swiper-rtl swiper-backface-hidden" dir="rtl">
            <div class="swiper-wrapper s-slider-swiper-wrapper" style="display:flex; transition-duration: 0ms; transform: translate3d(740px, 0px, 0px);">
                <?php

                // $product_ids = explode(',', sanitize_text_field($attr['ids']));
                // $category = sanitize_text_field($attr['category']);

                // Build the query arguments based on priority
                $query_args = array(
                    'post_type'      => 'product',
                    'posts_per_page' => 6,
                    'post_status'    => 'publish',
                );

                // if (!empty($product_ids) && $attr['ids']) {

                //     $query_args['post__in'] = $product_ids;
                // } elseif (!empty($category) && $attr['category']) {

                //     $query_args['tax_query'] = array(
                //         array(
                //             'taxonomy' => 'product_cat',
                //             'field'    => 'slug',
                //             'terms'    => $category,
                //         ),
                //     );
                // }

                // if ($attr['orderby'] === 'popularity') {

                //     $query_args['orderby'] = 'popularity';
                // } elseif ($attr['orderby'] === 'discount') {

                //     $query_args['meta_query']  = array(
                //         'relation' => 'OR',
                //         array(
                //             'key'           => '_sale_price',
                //             'value'         => 0,
                //             'compare'       => '>',
                //             'type'          => 'NUMERIC'
                //         ),
                //         array(
                //             'key'           => '_min_variation_sale_price',
                //             'value'         => 0,
                //             'compare'       => '>',
                //             'type'          => 'NUMERIC'
                //         )
                //     );
                // }

                $products = new WP_Query($query_args);

                if ($products->have_posts()) {
                    while ($products->have_posts()) {
                        $products->the_post();
                ?>

                        <div class="slide--one-fourth swiper-slide" role="group">
                            <?php get_template_part('template-parts/product/product', 'product'); ?>
                        </div>

                <?php
                    }
                    wp_reset_postdata();
                } else {
                    _e('No  product found.', 'mahalik');
                }

                ?>
            </div>
        </div>
    </salla-slider>
    <script>
        new Swiper('.<?php echo $swiper_id; ?>', {
            direction: 'horizontal',
            // reverseDirection: true,
            slidesPerView: 4,
            loop: true,
            // initialSlide: 0,

            // Navigation arrows
            navigation: {
                nextEl: '.<?php echo $swiper_id; ?>-next',
                prevEl: '.<?php echo $swiper_id; ?>-prev',
            },
        });
    </script>

</section>