<?php
add_shortcode('mahalik_product', 'mahalik_product_shortcode_callback');
if (!function_exists('mahalik_product_shortcode_callback')) {

    function mahalik_product_shortcode_callback($attributes)
    {
        $attr = shortcode_atts(array(
            'ids'       => false,
            'category'  => false,
            'orderby'   => 'popularity', // or discount
            'title'     => __('Best Seller', 'mahalik'),
            'qty'       => 6
        ), $attributes);

        ob_start();

        $swiper_id = uniqid('swiper_');
?>
        <section class="s-block s-block--best-offers container overflow-hidden">
            <salla-slider type="carousel" class="s-slider-wrapper carousel-slider s-slider-horizontal hydrated">
                <div class="s-slider-block__title">
                    <div class="s-slider-block__title-right">
                        <h2><?php echo $attr['title']; ?></h2>
                    </div>
                    <div class="s-slider-block__title-left">
                        <div class="s-slider-block__title-nav">
                            <button aria-label="Previous slide" class="<?php echo $swiper_id; ?>-prev s-slider-prev s-slider-nav-arrow">
                                <span class="s-slider-button-icon">
                                    <!-- Generated by IcoMoon.io -->
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                        <title>keyboard_arrow_right</title>
                                        <path d="M11.438 22.479l6.125-6.125-6.125-6.125 1.875-1.875 8 8-8 8z"></path>
                                    </svg>
                                </span>
                            </button>
                            <button aria-label="Next slide" class="<?php echo $swiper_id; ?>-next s-slider-next s-slider-nav-arrow">
                                <span class="s-slider-button-icon">
                                    <!-- Generated by IcoMoon.io -->
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                        <title>keyboard_arrow_left</title>
                                        <path d="M20.563 22.104l-1.875 1.875-8-8 8-8 1.875 1.875-6.125 6.125z"></path>
                                    </svg>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="swiper <?php echo $swiper_id; ?> s-slider-container swiper-initialized swiper-horizontal swiper-pointer-events swiper-rtl swiper-backface-hidden" dir="rtl">
                    <div class="swiper-wrapper s-slider-swiper-wrapper" style="transition-duration: 0ms; transform: translate3d(740px, 0px, 0px);">
                        <?php

                        $product_ids = explode(',', sanitize_text_field($attr['ids']));
                        $category = sanitize_text_field($attr['category']);

                        // Build the query arguments based on priority
                        $query_args = array(
                            'post_type'      => 'product',
                            'posts_per_page' => $attr['qty'],
                            'post_status'    => 'publish',
                        );

                        if (!empty($product_ids) && $attr['ids']) {

                            $query_args['post__in'] = $product_ids;
                        } elseif (!empty($category) && $attr['category']) {

                            $query_args['tax_query'] = array(
                                array(
                                    'taxonomy' => 'product_cat',
                                    'field'    => 'slug',
                                    'terms'    => $category,
                                ),
                            );
                        }

                        if ($attr['orderby'] === 'popularity') {

                            $query_args['orderby'] = 'popularity';
                        } elseif ($attr['orderby'] === 'discount') {

                            $query_args['meta_query']  = array(
                                'relation' => 'OR',
                                array(
                                    'key'           => '_sale_price',
                                    'value'         => 0,
                                    'compare'       => '>',
                                    'type'          => 'NUMERIC'
                                ),
                                array(
                                    'key'           => '_min_variation_sale_price',
                                    'value'         => 0,
                                    'compare'       => '>',
                                    'type'          => 'NUMERIC'
                                )
                            );
                        }

                        $products = new WP_Query($query_args);

                        if ($products->have_posts()) {
                            while ($products->have_posts()) {
                                $products->the_post();
                        ?>

                                <div class="slide--one-fourth swiper-slide" role="group">
                                    <?php get_template_part('template-parts/product/product', 'product'); ?>
                                </div>

                        <?php
                            }
                            wp_reset_postdata();
                        } else {
                            _e('No  product found.', 'mahalik');
                        }

                        ?>
                    </div>
                </div>
            </salla-slider>
            <script>
                new Swiper('.<?php echo $swiper_id; ?>', {
                    direction: 'horizontal',
                    // reverseDirection: true,
                    slidesPerView: 4,
                    loop: false,
                    initialSlide: 0,

                    // Navigation arrows
                    navigation: {
                        nextEl: '.<?php echo $swiper_id; ?>-next',
                        prevEl: '.<?php echo $swiper_id; ?>-prev',
                    },
                });
            </script>
        </section>


<?php
        $content = ob_get_contents();
        ob_clean();
        return $content;
    }
}
