<?php
add_shortcode('mahalik_archive_1', 'mahalik_archive_1_shortcode_callback');
if (!function_exists('mahalik_archive_1_shortcode_callback')) {

    function mahalik_archive_1_shortcode_callback($attributes)
    {
        $attr = shortcode_atts(array(
            'category' => 'something',
            'title' => 'Best Seller',
            'qty'   => 6
        ), $attributes);

        ob_start();
?>
        <section class="s-block s-block--best-offers container overflow-hidden">
            <salla-slider type="carousel" class="s-slider-wrapper carousel-slider s-slider-horizontal hydrated">
                <div class="s-slider-block__title">
                    <div class="s-slider-block__title-right">
                        <h2><?php echo $attr['title']; ?></h2>
                    </div>
                    <div class="s-slider-block__title-left">
                        <div class="s-slider-block__title-nav">
                            <button aria-label="Previous slide" class="swiper-1-prev s-slider-prev s-slider-nav-arrow">
                                <span class="s-slider-button-icon">
                                    <!-- Generated by IcoMoon.io -->
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                        <title>keyboard_arrow_right</title>
                                        <path d="M11.438 22.479l6.125-6.125-6.125-6.125 1.875-1.875 8 8-8 8z"></path>
                                    </svg>
                                </span>
                            </button>
                            <button aria-label="Next slide" class="swiper-1-next s-slider-next s-slider-nav-arrow">
                                <span class="s-slider-button-icon">
                                    <!-- Generated by IcoMoon.io -->
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                        <title>keyboard_arrow_left</title>
                                        <path d="M20.563 22.104l-1.875 1.875-8-8 8-8 1.875 1.875-6.125 6.125z"></path>
                                    </svg>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="swiper product-swiper-1 s-slider-container swiper-initialized swiper-horizontal swiper-pointer-events swiper-rtl swiper-backface-hidden" dir="rtl">
                    <div class="swiper-wrapper s-slider-swiper-wrapper" style="transition-duration: 0ms; transform: translate3d(740px, 0px, 0px);">
                        <?php $args = array(
                            'post_type'      => 'product',
                            'posts_per_page' => $attr['qty'],
                            // 'meta_query'     => array(
                            //     array(
                            //         'key'   => '_featured',  // TODO: Replace with your actual custom field key for featured products
                            //         'value' => 'yes',         // TODO: Replace with the value you use to mark a product as featured
                            //     ),
                            // ),
                        );

                        $featured_products = new WP_Query($args);

                        if ($featured_products->have_posts()) {
                            $i = 1; // Use as slide index
                            while ($featured_products->have_posts()) {
                                $featured_products->the_post();
                        ?>

                                <div class="slide--one-fourth swiper-slide" role="group">
                                    <?php get_template_part('template-parts/product/product', 'slide'); ?>
                                </div>

                        <?php
                                $i++;
                            }
                            wp_reset_postdata();
                        } else {
                            echo 'No featured products found.';
                        }

                        ?>
                    </div>
                    <!-- <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span> -->
                </div>
            </salla-slider>
        </section>

<?php
        $content = ob_get_contents();
        ob_clean();
        return $content;
    }
}
